In [45]:
 # import libraries 
import pandas as pd 
import numpy as np 
from scipy import stats 
import statsmodels.formula.api as smf
# Plotting Libraries 
import matplotlib.pyplot as plt 
import seaborn as sns
%matplotlib inline 
plt.style.use('seaborn-white')
## Setting Random Seeds for reproducibility 
np.random.seed(1234) 
import os 
os.environ['PYTHONHASHSEED']='1234' 
import random as rn
rn.seed(1234) 


In [46]:
 # Read Data 
df = pd.read_csv('AutoData.csv') # Reads Data 
df = df.dropna() # Drops 
df.head(5) # Prints a few observations from the data

mpg  cylinder  displacement  horsepower  weight  accelaration  model_year  \
0  18.0         8         307.0         130    3504          12.0          70   
1  15.0         8         350.0         165    3693          11.5          70   
2  18.0         8         318.0         150    3436          11.0          70   
3  16.0         8         304.0         150    3433          12.0          70   
4  17.0         8         302.0         140    3449          10.5          70   

   origin                   car_name  
0       1  chevrolet chevelle malibu  
1       1          buick skylark 320  
2       1         plymouth satellite  
3       1              amc rebel sst  
4       1                ford torino

In [47]:
print('Number of Observations:',df.shape[0]) 
print('Number of Variables:',df.shape[1])


Number of Observations: 392
Number of Variables: 9


In [48]:
# Read the dataset provided in Blackboard for Student Grades
Data = np.genfromtxt("AutoData.csv", delimiter=",", skip_header = 1) # Doesn't read the header
# Check the Size of the data set
print('Number of Observations:', Data.shape[0])
print('Number of Variables:', Data.shape[1])
# Define the Predictor and target values
x = Data[:, [2,3,4,5]]    #x variables (displacement, horsepower, weight, acceleration)
x[:,0] /= np.max(x[:,0])                           # Normalize the Data
x[:,1] /= np.max(x[:,1])
x[:,2] /= np.max(x[:,2])
x[:,3] /= np.max(x[:,3])

x=np.insert(x,0,1, axis=1)       #insert column of ones
y = Data[:, 0]                           # mpg
#print(x)
print(y)

Number of Observations: 392
Number of Variables: 9
[18.  15.  18.  16.  17.  15.  14.  14.  14.  15.  15.  14.  15.  14.
 24.  22.  18.  21.  27.  26.  25.  24.  25.  26.  21.  10.  10.  11.
  9.  27.  28.  25.  19.  16.  17.  19.  18.  14.  14.  14.  14.  12.
 13.  13.  18.  22.  19.  18.  23.  28.  30.  30.  31.  35.  27.  26.
 24.  25.  23.  20.  21.  13.  14.  15.  14.  17.  11.  13.  12.  13.
 19.  15.  13.  13.  14.  18.  22.  21.  26.  22.  28.  23.  28.  27.
 13.  14.  13.  14.  15.  12.  13.  13.  14.  13.  12.  13.  18.  16.
 18.  18.  23.  26.  11.  12.  13.  12.  18.  20.  21.  22.  18.  19.
 21.  26.  15.  16.  29.  24.  20.  19.  15.  24.  20.  11.  20.  19.
 15.  31.  26.  32.  25.  16.  16.  18.  16.  13.  14.  14.  14.  29.
 26.  26.  31.  32.  28.  24.  26.  24.  26.  31.  19.  18.  15.  15.
 16.  15.  16.  14.  17.  16.  15.  18.  21.  20.  13.  29.  23.  20.
 23.  24.  25.  24.  18.  29.  19.  23.  23.  22.  25.  33.  28.  25.
 25.  26.  27.  17.5 16.  15.5 14.5 22.

In [49]:
# Split the data into Train-Test
# We will first Randomize the data and then pick a portion of the data as Test data
Test_data_points = np.floor(.30*len(x))  #solve for the first 30% of the data
Train_data_points = np.floor(.70*len(x))   #solve for remaining 70% of the data

Test_data_points=Test_data_points.astype(int)
Train_data_points=Train_data_points.astype(int)

print(Test_data_points)
print(Train_data_points)

# Split the Data
x_train = x[0:Train_data_points,:]    #assign first 30% to train set
x_test  = x[Train_data_points:len(x),:]  #assign remaining 70% to test set
y_train = y[0:Train_data_points]
y_test  = y[Train_data_points:len(x)]

#print(x_test)
print(y_train.shape)
print(y_train)

117
274
(274,)
[18.  15.  18.  16.  17.  15.  14.  14.  14.  15.  15.  14.  15.  14.
 24.  22.  18.  21.  27.  26.  25.  24.  25.  26.  21.  10.  10.  11.
  9.  27.  28.  25.  19.  16.  17.  19.  18.  14.  14.  14.  14.  12.
 13.  13.  18.  22.  19.  18.  23.  28.  30.  30.  31.  35.  27.  26.
 24.  25.  23.  20.  21.  13.  14.  15.  14.  17.  11.  13.  12.  13.
 19.  15.  13.  13.  14.  18.  22.  21.  26.  22.  28.  23.  28.  27.
 13.  14.  13.  14.  15.  12.  13.  13.  14.  13.  12.  13.  18.  16.
 18.  18.  23.  26.  11.  12.  13.  12.  18.  20.  21.  22.  18.  19.
 21.  26.  15.  16.  29.  24.  20.  19.  15.  24.  20.  11.  20.  19.
 15.  31.  26.  32.  25.  16.  16.  18.  16.  13.  14.  14.  14.  29.
 26.  26.  31.  32.  28.  24.  26.  24.  26.  31.  19.  18.  15.  15.
 16.  15.  16.  14.  17.  16.  15.  18.  21.  20.  13.  29.  23.  20.
 23.  24.  25.  24.  18.  29.  19.  23.  23.  22.  25.  33.  28.  25.
 25.  26.  27.  17.5 16.  15.5 14.5 22.  22.  24.  22.5 29.  24.5 29.
 33. 

In [50]:
# Gradient Descent Function
def Gradient_Descent_Function(m, x, y):
    y_predict=np.matmul(x,m)
   # y_predict = x.dot(m).flatten()
    #print(m)
    #print(y_predict)
    
    
    Error     =  (y.flatten() - y_predict)
    #print(Error)
    
    MSE       =  (2.0/len(x)) * np.sum(np.power(Error, 2))
    #Gradient  = -(2.0/len(x)) * Error.dot(x)
    #Gradient  = -(2.0/len(x)) * np.matmul(Error,x)
    Gradient  = -(1.0/len(x)) * np.matmul(Error,x)
    print(MSE)
    print("next")
    return Gradient, MSE

In [51]:
# Define a function to run the calculation
def Calculate_Parameters(alpha, t, x_train, y_train, x_test, y_test, 
                         RUN_OPTIMIZATION = True, Print_Updates= True, Plot_Fitted_Model = False, Plot_Gradient= False):
    m     = np.random.randn(5)*1  # Random initialization of the parameters
    #m=[40,-.009,-.018,-.0045,-.073]
   # m=m.transpose()
   # print(m.shape)
    BB=np.array([0, 5, 6, 7])
    #print(BB.shape)
                                # Here, m has two parameters for both intercept and slop
    count = 1                   # Count Number of Iterations it took to minimize the loss function
    StuckCheck = 0              # To check if its stuck in a search repetation
    while RUN_OPTIMIZATION:
        # Calculate the Gradient
        Grad, MSE = Gradient_Descent_Function(m, x_train, y_train)
        # Update the parameters
        m_updated = m - (alpha * Grad)
        print(m)
        print(Grad)
        print(m_updated)
        #print(Grad)
        
        # Checking with a threshold if it's stuck in loop
        StuckCheck += 1
        if StuckCheck > 10_000:
            print('Stopping the Optimization as it\'s Stuck in a search loop')
            break
            
        # Stop updating the gradient if it reaches certain toleranec limit
        if np.sum(abs(m_updated - m)) < t:
            RUN_OPTIMIZATION = False
            print('Optimization Operation Complete!!')
        
        # Print Updates
        if Print_Updates:
            # print the MSE Errors every 100 iterations to check how the error is reduced
            if count % 100 == 0:
                print('Iteration: %d and Error:%f \n' % (count, MSE))

        count += 1
        m = m_updated
        
        # Plot the fitted Model
       # if Plot_Fitted_Model:
        #    if count % 50 == 0:
         #       Plotting_Fitted_Model(x_train, x_test, y_train, y_test, m)
            
    # Plot Gradient
    #if Plot_Gradient:
     #   Plot_Gradients(m, x_train, y_train)
            
    #print('Optimization operation took %d iterations' % count)
    return m, count

In [52]:
# Select initial Hyper parameters
#alpha = .000000185               # Learning Rate
alpha = .6 
t     = 1e-6   

In [53]:
if __name__ == '__main__':
    m,count = Calculate_Parameters(alpha, t, x_train, y_train, x_test, y_test,
                                   RUN_OPTIMIZATION  = True, 
                                   Print_Updates     = True, 
                                   Plot_Fitted_Model = True, 
                                   Plot_Gradient     = False)

929.0425793138974
next
[ 0.47143516 -1.19097569  1.43270697 -0.3126519  -0.72058873]
[-20.62974824  -8.47246627  -9.19104059 -11.61546272 -12.96816398]
[12.84928411  3.89250407  6.94733132  6.65662574  7.06030965]
224.64419760962306
next
[12.84928411  3.89250407  6.94733132  6.65662574  7.06030965]
[5.85905123 4.70424774 4.21066049 5.01420723 3.10514299]
[9.33385337 1.06995543 4.42093503 3.6481014  5.19722386]
131.644787727558
next
[9.33385337 1.06995543 4.42093503 3.6481014  5.19722386]
[-3.20069016  0.07157751 -0.46390874 -0.75973755 -2.34888882]
[11.25426747  1.02700892  4.69928027  4.10394393  6.60655715]
112.11610575991459
next
[11.25426747  1.02700892  4.69928027  4.10394393  6.60655715]
[-0.02404874  1.57597446  1.08859272  1.18263238 -0.39524673]
[11.26869671  0.08142425  4.04612464  3.3943645   6.84370519]
102.18398430591778
next
[11.26869671  0.08142425  4.04612464  3.3943645   6.84370519]
[-1.06355692  0.97221715  0.50016539  0.47066014 -0.99623766]
[11.90683087 -0.50190604 

[ 29.55546761 -11.68574975   0.75256691 -13.22386791   6.91099312]
[-0.03983498 -0.01028013 -0.00654991  0.04114229  0.03696788]
[ 29.5793686  -11.67958167   0.75649685 -13.24855328   6.8888124 ]
18.787883552511698
next
[ 29.5793686  -11.67958167   0.75649685 -13.24855328   6.8888124 ]
[-0.03971758 -0.01030697 -0.00646354  0.04102603  0.03684467]
[ 29.60319915 -11.67339749   0.76037497 -13.2731689    6.86670559]
18.7764618077136
next
[ 29.60319915 -11.67339749   0.76037497 -13.2731689    6.86670559]
[-0.03960059 -0.01033358 -0.00637761  0.04091016  0.03672194]
[ 29.6269595  -11.66719734   0.76420154 -13.297715     6.84467243]
18.765107998290162
next
[ 29.6269595  -11.66719734   0.76420154 -13.297715     6.84467243]
[-0.03948401 -0.01035997 -0.00629213  0.04079469  0.03659967]
[ 29.65064991 -11.66098135   0.76797682 -13.32219181   6.82271263]
18.753821644476652
next
[ 29.65064991 -11.66098135   0.76797682 -13.32219181   6.82271263]
[-0.03936785 -0.01038614 -0.00620709  0.0406796   0.036

[ 33.50152751 -10.10937357   0.73802673 -17.34032043   3.38688365]
17.32701066050843
next
[ 33.50152751 -10.10937357   0.73802673 -17.34032043   3.38688365]
[-0.02160927 -0.01231921  0.00452761  0.02274916  0.01839845]
[ 33.51449308 -10.10198204   0.73531016 -17.35396993   3.37584457]
17.323426154849955
next
[ 33.51449308 -10.10198204   0.73531016 -17.35396993   3.37584457]
[-0.02155405 -0.01231638  0.00455123  0.02269203  0.01834455]
[ 33.52742551 -10.09459221   0.73257942 -17.36758514   3.36483784]
17.319857983707195
next
[ 33.52742551 -10.09459221   0.73257942 -17.36758514   3.36483784]
[-0.021499   -0.01231348  0.00457468  0.02263507  0.01829084]
[ 33.54032491 -10.08720413   0.72983461 -17.38116618   3.35386334]
17.316306053627134
next
[ 33.54032491 -10.08720413   0.72983461 -17.38116618   3.35386334]
[-0.02144414 -0.01231051  0.00459798  0.02257828  0.01823732]
[ 33.55319139 -10.07981782   0.72707582 -17.39471315   3.34292095]
17.312770271800172
next
[ 33.55319139 -10.07981782   0

[ 35.94828406  -8.37460951  -0.20141125 -19.91892095   1.38374746]
[-0.01193598 -0.01029638  0.00695148  0.01252965  0.00935148]
[ 35.95544565  -8.36843168  -0.20558213 -19.92643874   1.37813657]
16.76841172033004
next
[ 35.95544565  -8.36843168  -0.20558213 -19.92643874   1.37813657]
[-0.01191017 -0.01028558  0.00695183  0.01250169  0.00932873]
[ 35.96259175  -8.36226033  -0.20975323 -19.93393975   1.37253933]
16.767118593730515
next
[ 35.96259175  -8.36226033  -0.20975323 -19.93393975   1.37253933]
[-0.01188442 -0.01027478  0.00695214  0.0124738   0.00930604]
[ 35.9697224   -8.35609547  -0.21392452 -19.94142404   1.36695571]
16.76583014132667
next
[ 35.9697224   -8.35609547  -0.21392452 -19.94142404   1.36695571]
[-0.01185875 -0.01026397  0.00695241  0.01244599  0.00928343]
[ 35.97683765  -8.34993708  -0.21809596 -19.94889163   1.36138565]
16.764546343306964
next
[ 35.97683765  -8.34993708  -0.21809596 -19.94889163   1.36138565]
[-0.01183315 -0.01025315  0.00695263  0.01241825  0.009

[ 37.42486883  -6.95390902  -1.26746084 -21.4491148    0.25773004]
[-0.00697751 -0.00739646  0.0060568   0.00707886  0.0051883 ]
[ 37.42905534  -6.94947114  -1.27109492 -21.45336212   0.25461706]
16.542573005629055
next
[ 37.42905534  -6.94947114  -1.27109492 -21.45336212   0.25461706]
[-0.00696454 -0.0073863   0.00605142  0.0070644   0.00517805]
[ 37.43323407  -6.94503936  -1.27472577 -21.45760076   0.25151023]
16.54205406894739
next
[ 37.43323407  -6.94503936  -1.27472577 -21.45760076   0.25151023]
[-0.0069516  -0.00737616  0.00604603  0.00704998  0.00516782]
[ 37.43740502  -6.94061367  -1.27835339 -21.46183074   0.24840954]
16.541536821581115
next
[ 37.43740502  -6.94061367  -1.27835339 -21.46183074   0.24840954]
[-0.00693869 -0.00736602  0.00604063  0.00703559  0.00515762]
[ 37.44156824  -6.93619406  -1.28197777 -21.4660521    0.24531497]
16.541021257671055
next
[ 37.44156824  -6.93619406  -1.28197777 -21.4660521    0.24531497]
[-0.00692581 -0.00735589  0.00603523  0.00702123  0.00

16.45214581872191
next
[ 38.28492486  -6.00154601  -2.08763245 -22.30002069  -0.37614874]
[-0.00444501 -0.00510015  0.00461483  0.00425064  0.00326077]
[ 38.28759187  -5.99848592  -2.09040134 -22.30257108  -0.3781052 ]
16.451916159198575
next
[ 38.28759187  -5.99848592  -2.09040134 -22.30257108  -0.3781052 ]
[-0.00443757 -0.00509243  0.00460935  0.00424235  0.00325532]
[ 38.29025441  -5.99543046  -2.09316695 -22.30511648  -0.38005839]
16.451687222170452
next
[ 38.29025441  -5.99543046  -2.09316695 -22.30511648  -0.38005839]
[-0.00443014 -0.00508473  0.00460386  0.00423407  0.00324989]
[ 38.29291249  -5.99237962  -2.09592927 -22.30765693  -0.38200833]
16.451459005306255
next
[ 38.29291249  -5.99237962  -2.09592927 -22.30765693  -0.38200833]
[-0.00442272 -0.00507703  0.00459838  0.00422581  0.00324447]
[ 38.29556612  -5.98933341  -2.0986883  -22.31019241  -0.38395501]
16.451231506282564
next
[ 38.29556612  -5.98933341  -2.0986883  -22.31019241  -0.38395501]
[-0.00441532 -0.00506934  0.00

[ 38.84321563  -5.35378061  -2.69558579 -22.81513468  -0.78738304]
[-0.00293933 -0.00342538  0.00334436  0.0025905   0.00218339]
[ 38.84497922  -5.35172539  -2.69759241 -22.81668898  -0.78869307]
16.41154910070844
next
[ 38.84497922  -5.35172539  -2.69759241 -22.81668898  -0.78869307]
[-0.00293473 -0.00341994  0.00333998  0.00258552  0.00218016]
[ 38.84674006  -5.34967342  -2.6995964  -22.81824029  -0.79000117]
16.411446215280318
next
[ 38.84674006  -5.34967342  -2.6995964  -22.81824029  -0.79000117]
[-0.00293015 -0.00341451  0.00333561  0.00258055  0.00217694]
[ 38.84849815  -5.34762471  -2.70159777 -22.81978862  -0.79130734]
16.411343648518695
next
[ 38.84849815  -5.34762471  -2.70159777 -22.81978862  -0.79130734]
[-0.00292557 -0.00340909  0.00333125  0.00257558  0.00217373]
[ 38.85025349  -5.34557926  -2.70359652 -22.82133397  -0.79261158]
16.41124139942103
next
[ 38.85025349  -5.34557926  -2.70359652 -22.82133397  -0.79261158]
[-0.002921   -0.00340368  0.00332689  0.00257063  0.002

16.39327458920038
next
[ 39.21901632  -4.91921434  -3.13424331 -23.13137978  -1.07000964]
[-0.00198213 -0.00225992  0.00236966  0.00157377  0.00151513]
[ 39.2202056   -4.91785839  -3.13566511 -23.13232404  -1.07091872]
16.393228007789567
next
[ 39.2202056   -4.91785839  -3.13566511 -23.13232404  -1.07091872]
[-0.00197917 -0.00225623  0.00236646  0.00157072  0.00151307]
[ 39.2213931   -4.91650465  -3.13708499 -23.13326647  -1.07182656]
16.39318156890887
next
[ 39.2213931   -4.91650465  -3.13708499 -23.13326647  -1.07182656]
[-0.00197622 -0.00225255  0.00236326  0.00156766  0.00151101]
[ 39.22257883  -4.91515312  -3.13850294 -23.13420707  -1.07273317]
16.39313527211527
next
[ 39.22257883  -4.91515312  -3.13850294 -23.13420707  -1.07273317]
[-0.00197326 -0.00224888  0.00236006  0.00156462  0.00150895]
[ 39.22376279  -4.91380379  -3.13991897 -23.13514584  -1.07363854]
16.39308911696716
next
[ 39.22376279  -4.91380379  -3.13991897 -23.13514584  -1.07363854]
[-0.00197032 -0.00224521  0.00235

16.38536024827578
next
[ 39.45858837  -4.65095418  -3.42458162 -23.31174442  -1.25604895]
[-0.00139397 -0.00152444  0.0017117   0.00098275  0.00110299]
[ 39.45942475  -4.65003952  -3.42560864 -23.31233407  -1.25671074]
16.385337754780657
next
[ 39.45942475  -4.65003952  -3.42560864 -23.31233407  -1.25671074]
[-0.00139194 -0.00152191  0.00170937  0.00098079  0.00110156]
[ 39.46025991  -4.64912637  -3.42663426 -23.31292255  -1.25737167]
16.385315329251547
next
[ 39.46025991  -4.64912637  -3.42663426 -23.31292255  -1.25737167]
[-0.00138992 -0.00151938  0.00170704  0.00097883  0.00110013]
[ 39.46109387  -4.64821474  -3.42765849 -23.31350984  -1.25803175]
16.38529297147917
next
[ 39.46109387  -4.64821474  -3.42765849 -23.31350984  -1.25803175]
[-0.00138791 -0.00151686  0.00170471  0.00097687  0.0010987 ]
[ 39.46192661  -4.64730463  -3.42868132 -23.31409597  -1.25869097]
16.385270681254937
next
[ 39.46192661  -4.64730463  -3.42868132 -23.31409597  -1.25869097]
[-0.00138589 -0.00151434  0.001

16.38150038756332
next
[ 39.62898452  -4.46931064  -3.63567632 -23.42426849  -1.39334151]
[-0.00098612 -0.00101851  0.00123249  0.00060034  0.00081133]
[ 39.6295762   -4.46869953  -3.63641581 -23.4246287   -1.39382831]
16.381489481690636
next
[ 39.6295762   -4.46869953  -3.63641581 -23.4246287   -1.39382831]
[-0.00098472 -0.0010168   0.00123082  0.00059908  0.00081031]
[ 39.63016703  -4.46808946  -3.6371543  -23.42498814  -1.3943145 ]
16.381478608267493
next
[ 39.63016703  -4.46808946  -3.6371543  -23.42498814  -1.3943145 ]
[-0.00098333 -0.00101508  0.00122914  0.00059783  0.0008093 ]
[ 39.63075703  -4.46748041  -3.63789179 -23.42534684  -1.39480008]
16.38146776719504
next
[ 39.63075703  -4.46748041  -3.63789179 -23.42534684  -1.39480008]
[-0.00098193 -0.00101337  0.00122747  0.00059657  0.00080828]
[ 39.63134619  -4.46687238  -3.63862827 -23.42570478  -1.39528505]
16.381456958374756
next
[ 39.63134619  -4.46687238  -3.63862827 -23.42570478  -1.39528505]
[-0.00098054 -0.00101167  0.001

[ 39.76151888  -4.33716701  -3.8024861  -23.49797302  -1.50474651]
[-0.00067564 -0.00064494  0.00085659  0.00033429  0.00058208]
[ 39.76192426  -4.33678005  -3.80300006 -23.49817359  -1.50509575]
16.379470148905884
next
[ 39.76192426  -4.33678005  -3.80300006 -23.49817359  -1.50509575]
[-0.0006747  -0.00064384  0.00085544  0.00033353  0.00058137]
[ 39.76232908  -4.33639374  -3.80351332 -23.49837371  -1.50544457]
16.379465230680136
next
[ 39.76232908  -4.33639374  -3.80351332 -23.49837371  -1.50544457]
[-0.00067376 -0.00064274  0.00085429  0.00033278  0.00058066]
[ 39.76273334  -4.3360081   -3.8040259  -23.49857338  -1.50579297]
16.379460326778744
next
[ 39.76273334  -4.3360081   -3.8040259  -23.49857338  -1.50579297]
[-0.00067282 -0.00064164  0.00085314  0.00033202  0.00057996]
[ 39.76313703  -4.33562312  -3.80453778 -23.49877259  -1.50614094]
16.37945543715874
next
[ 39.76313703  -4.33562312  -3.80453778 -23.49877259  -1.50614094]
[-0.00067189 -0.00064054  0.000852    0.00033127  0.00

[ 39.8475459   -4.25822617  -3.91212665 -23.53606252  -1.58040789]
16.378593948218317
next
[ 39.8475459   -4.25822617  -3.91212665 -23.53606252  -1.58040789]
[-0.000478   -0.00041822  0.00061266  0.00018312  0.00043031]
[ 39.8478327   -4.25797524  -3.91249424 -23.53617239  -1.58066607]
16.378591556058723
next
[ 39.8478327   -4.25797524  -3.91249424 -23.53617239  -1.58066607]
[-0.00047735 -0.00041749  0.00061185  0.00018266  0.00042979]
[ 39.84811912  -4.25772475  -3.91286135 -23.53628198  -1.58092395]
16.378589170700433
next
[ 39.84811912  -4.25772475  -3.91286135 -23.53628198  -1.58092395]
[-0.0004767  -0.00041676  0.00061104  0.00018219  0.00042928]
[ 39.84840514  -4.25747469  -3.91322798 -23.5363913   -1.58118152]
16.3785867921234
next
[ 39.84840514  -4.25747469  -3.91322798 -23.5363913   -1.58118152]
[-0.00047605 -0.00041604  0.00061023  0.00018173  0.00042877]
[ 39.84869077  -4.25722507  -3.91359411 -23.53650033  -1.58143878]
16.37858442030764
next
[ 39.84869077  -4.25722507  -3.9

[ 39.91101784  -4.20529137  -3.99387642 -23.55678907  -1.63879831]
16.3781492014951
next
[ 39.91101784  -4.20529137  -3.99387642 -23.55678907  -1.63879831]
[-3.34831579e-04 -2.63469160e-04  4.33580232e-04  8.76264814e-05
  3.15614212e-04]
[ 39.91121874  -4.20513329  -3.99413657 -23.55684164  -1.63898768]
16.37814805793941
next
[ 39.91121874  -4.20513329  -3.99413657 -23.55684164  -1.63898768]
[-3.34382879e-04 -2.63001892e-04  4.33015534e-04  8.73523971e-05
  3.15246109e-04]
[ 39.91141937  -4.20497549  -3.99439638 -23.55689405  -1.63917682]
16.378146917539418
next
[ 39.91141937  -4.20497549  -3.99439638 -23.55689405  -1.63917682]
[-3.33934812e-04 -2.62535413e-04  4.32451609e-04  8.70788831e-05
  3.14878462e-04]
[ 39.91161973  -4.20481797  -3.99465585 -23.5569463   -1.63936575]
16.378145780286044
next
[ 39.91161973  -4.20481797  -3.99465585 -23.5569463   -1.63936575]
[-3.33487377e-04 -2.62069722e-04  4.31888457e-04  8.68059382e-05
  3.14511270e-04]
[ 39.91181982  -4.20466073  -3.99491499

[ 39.95259796  -4.17420654  -4.04794857 -23.56543439  -1.67877561]
[-2.42712141e-04 -1.70663216e-04  3.17119026e-04  3.57219228e-05
  2.38526452e-04]
[ 39.95274359  -4.17410415  -4.04813884 -23.56545583  -1.67891873]
16.377945968396077
next
[ 39.95274359  -4.17410415  -4.04813884 -23.56545583  -1.67891873]
[-2.42392443e-04 -1.70353671e-04  3.16712845e-04  3.55591939e-05
  2.38252864e-04]
[ 39.95288902  -4.17400193  -4.04832886 -23.56547716  -1.67906168]
16.377945378126412
next
[ 39.95288902  -4.17400193  -4.04832886 -23.56547716  -1.67906168]
[-2.42073190e-04 -1.70044656e-04  3.16307212e-04  3.53968288e-05
  2.37979608e-04]
[ 39.95303427  -4.17389991  -4.04851865 -23.5654984   -1.67920447]
Iteration: 3300 and Error:16.377945 

16.377944789435514
next
[ 39.95303427  -4.17389991  -4.04851865 -23.5654984   -1.67920447]
[-2.41754380e-04 -1.69736170e-04  3.15902128e-04  3.52348267e-05
  2.37706683e-04]
[ 39.95317932  -4.17379806  -4.04870819 -23.56551954  -1.67934709]
16.377944202318968
nex

  1.78029584e-04]
[ 39.98449925  -4.15313393  -4.08981253 -23.56827674  -1.71077731]
16.377835794363385
next
[ 39.98449925  -4.15313393  -4.08981253 -23.56827674  -1.71077731]
[-1.73286356e-04 -1.06113520e-04  2.28517266e-04  4.06073945e-06
  1.77828687e-04]
[ 39.98460322  -4.15307026  -4.08994964 -23.56827917  -1.710884  ]
16.37783549420229
next
[ 39.98460322  -4.15307026  -4.08994964 -23.56827917  -1.710884  ]
[-1.73062314e-04 -1.05915171e-04  2.28229912e-04  3.97223193e-06
  1.77628028e-04]
[ 39.98470706  -4.15300672  -4.09008658 -23.56828156  -1.71099058]
16.377835194815713
next
[ 39.98470706  -4.15300672  -4.09008658 -23.56828156  -1.71099058]
[-1.72838579e-04 -1.05717166e-04  2.27942940e-04  3.88394623e-06
  1.77427608e-04]
[ 39.98481076  -4.15294328  -4.09022335 -23.56828389  -1.71109704]
16.377834896201545
next
[ 39.98481076  -4.15294328  -4.09022335 -23.56828389  -1.71109704]
[-1.72615148e-04 -1.05519506e-04  2.27656349e-04  3.79588191e-06
  1.77227426e-04]
[ 39.98491433  -4.1

[ 40.0052121   -4.14124712  -4.11723213 -23.56767767  -1.73241424]
[-1.29005706e-04 -6.85139883e-05  1.71501855e-04 -1.12408672e-05
  1.37401038e-04]
[ 40.00528951  -4.14120601  -4.11733503 -23.56767093  -1.73249668]
16.37778336632601
next
[ 40.00528951  -4.14120601  -4.11733503 -23.56767093  -1.73249668]
[-1.28841690e-04 -6.83814411e-05  1.71289753e-04 -1.12883678e-05
  1.37248074e-04]
[ 40.00536681  -4.14116498  -4.1174378  -23.56766415  -1.73257903]
16.377783199436234
next
[ 40.00536681  -4.14116498  -4.1174378  -23.56766415  -1.73257903]
[-1.28677895e-04 -6.82491281e-05  1.71077930e-04 -1.13357284e-05
  1.37095288e-04]
[ 40.00544402  -4.14112403  -4.11754045 -23.56765735  -1.73266129]
16.377783032962878
next
[ 40.00544402  -4.14112403  -4.11754045 -23.56765735  -1.73266129]
[-1.28514320e-04 -6.81170487e-05  1.70866383e-04 -1.13829492e-05
  1.36942681e-04]
[ 40.00552113  -4.14108316  -4.11764297 -23.56765052  -1.73274346]
16.37778286690484
next
[ 40.00552113  -4.14108316  -4.1176429

  1.09732080e-04]
[ 40.01913684  -4.13432749  -4.13580595 -23.56581758  -1.74747258]
16.377756702870247
next
[ 40.01913684  -4.13432749  -4.13580595 -23.56581758  -1.74747258]
[-9.97085446e-05 -4.58128614e-05  1.33485033e-04 -1.83969548e-05
  1.09611266e-04]
[ 40.01919667  -4.1343      -4.13588604 -23.56580654  -1.74753835]
16.377756601622995
next
[ 40.01919667  -4.1343      -4.13588604 -23.56580654  -1.74753835]
[-9.95836583e-05 -4.57207202e-05  1.33322362e-04 -1.84211564e-05
  1.09490591e-04]
[ 40.01925642  -4.13427257  -4.13596603 -23.56579549  -1.74760404]
16.377756500621025
next
[ 40.01925642  -4.13427257  -4.13596603 -23.56579549  -1.74760404]
[-9.94589375e-05 -4.56287446e-05  1.33159900e-04 -1.84452668e-05
  1.09370055e-04]
[ 40.0193161   -4.13424519  -4.13604593 -23.56578442  -1.74766966]
16.37775639986374
next
[ 40.0193161   -4.13424519  -4.13604593 -23.56578442  -1.74766966]
[-9.93343821e-05 -4.55369342e-05  1.32997649e-04 -1.84692861e-05
  1.09249658e-04]
[ 40.0193757   -4.1

[ 40.0320398   -4.12892916  -4.15314865 -23.56271642  -1.7619104 ]
16.377737587999082
next
[ 40.0320398   -4.12892916  -4.15314865 -23.56271642  -1.7619104 ]
[-7.30056095e-05 -2.72153750e-05  9.85577434e-05 -2.20695894e-05
  8.32808055e-05]
[ 40.0320836   -4.12891283  -4.15320779 -23.56270318  -1.76196037]
16.377737532335157
next
[ 40.0320836   -4.12891283  -4.15320779 -23.56270318  -1.76196037]
[-7.29158319e-05 -2.71570444e-05  9.84397649e-05 -2.20762302e-05
  8.31902740e-05]
[ 40.03212735  -4.12889654  -4.15326685 -23.56268993  -1.76201028]
16.377737476801453
next
[ 40.03212735  -4.12889654  -4.15326685 -23.56268993  -1.76201028]
[-7.28261712e-05 -2.70988215e-05  9.83219359e-05 -2.20828194e-05
  8.30998451e-05]
[ 40.03217104  -4.12888028  -4.15332585 -23.56267668  -1.76206014]
16.377737421397633
next
[ 40.03217104  -4.12888028  -4.15332585 -23.56267668  -1.76206014]
[-7.27366273e-05 -2.70407060e-05  9.82042562e-05 -2.20893570e-05
  8.30095190e-05]
[ 40.03221469  -4.12886406  -4.15338

16.3777267656774
next
[ 40.04173752  -4.12571236  -4.16629218 -23.5592436   -1.77316339]
[-5.33037742e-05 -1.52599303e-05  7.25570383e-05 -2.23778620e-05
  6.30094469e-05]
[ 40.0417695   -4.1257032   -4.16633571 -23.55923017  -1.7732012 ]
16.37772673495168
next
[ 40.0417695   -4.1257032   -4.16633571 -23.55923017  -1.7732012 ]
[-5.32394344e-05 -1.52239980e-05  7.24717240e-05 -2.23746414e-05
  6.29417606e-05]
[ 40.04180144  -4.12569407  -4.1663792  -23.55921675  -1.77323896]
Iteration: 4500 and Error:16.377727 

16.377726704295487
next
[ 40.04180144  -4.12569407  -4.1663792  -23.55921675  -1.77323896]
[-5.31751769e-05 -1.51881344e-05  7.23865157e-05 -2.23713941e-05
  6.28741499e-05]
[ 40.04183335  -4.12568495  -4.16642263 -23.55920332  -1.77327669]
16.37772667370867
next
[ 40.04183335  -4.12568495  -4.16642263 -23.55920332  -1.77327669]
[-5.31110014e-05 -1.51523393e-05  7.23014135e-05 -2.23681200e-05
  6.28066149e-05]
[ 40.04186521  -4.12567586  -4.16646601 -23.5591899   -1.77331437]
16

[ 40.048814    -4.12396513  -4.17596071 -23.55589425  -1.78166153]
[-3.91895348e-05 -7.97997253e-06  5.37634782e-05 -2.08526613e-05
  4.78731256e-05]
[ 40.04883752  -4.12396034  -4.17599297 -23.55588174  -1.78169025]
16.377720741255253
next
[ 40.04883752  -4.12396034  -4.17599297 -23.55588174  -1.78169025]
[-3.91430807e-05 -7.95823173e-06  5.37013356e-05 -2.08446256e-05
  4.78222468e-05]
[ 40.048861    -4.12395557  -4.17602519 -23.55586923  -1.78171895]
16.377720723982808
next
[ 40.048861    -4.12395557  -4.17602519 -23.55586923  -1.78171895]
[-3.90966849e-05 -7.93653443e-06  5.36392688e-05 -2.08365780e-05
  4.77714241e-05]
[ 40.04888446  -4.1239508   -4.17605737 -23.55585673  -1.78174761]
16.377720706748335
next
[ 40.04888446  -4.1239508   -4.17605737 -23.55585673  -1.78174761]
[-3.90503473e-05 -7.91488056e-06  5.35772777e-05 -2.08285185e-05
  4.77206573e-05]
[ 40.04890789  -4.12394606  -4.17608952 -23.55584424  -1.78177624]
16.37772068955174
next
[ 40.04890789  -4.12394606  -4.176089

  3.90616134e-05]
[ 40.05287451  -4.12325441  -4.18154625 -23.55357596  -1.78667724]
16.37771803030226
next
[ 40.05287451  -4.12325441  -4.18154625 -23.55357596  -1.78667724]
[-3.12182427e-05 -4.50501847e-06  4.30670234e-05 -1.91264658e-05
  3.90204009e-05]
[ 40.05289324  -4.1232517   -4.18157209 -23.55356449  -1.78670065]
16.377718018937063
next
[ 40.05289324  -4.1232517   -4.18157209 -23.55356449  -1.78670065]
[-3.11817229e-05 -4.49037365e-06  4.30178535e-05 -1.91168247e-05
  3.89792334e-05]
[ 40.05291195  -4.12324901  -4.1815979  -23.55355302  -1.78672404]
16.377718007596396
next
[ 40.05291195  -4.12324901  -4.1815979  -23.55355302  -1.78672404]
[-3.11452483e-05 -4.47575950e-06  4.29687428e-05 -1.91071786e-05
  3.89381109e-05]
[ 40.05293064  -4.12324633  -4.18162368 -23.55354155  -1.7867474 ]
16.37771799628018
next
[ 40.05293064  -4.12324633  -4.18162368 -23.55354155  -1.7867474 ]
[-3.11088187e-05 -4.46117596e-06  4.29196912e-05 -1.90975274e-05
  3.88970332e-05]
[ 40.0529493   -4.12

[ 40.05724429  -4.12278886  -4.18759588 -23.55067456  -1.79221799]
[-2.27705461e-05 -1.48569148e-06  3.16455303e-05 -1.63960575e-05
  2.93216331e-05]
[ 40.05725795  -4.12278797  -4.18761487 -23.55066472  -1.79223558]
16.377715679099428
next
[ 40.05725795  -4.12278797  -4.18761487 -23.55066472  -1.79223558]
[-2.27443803e-05 -1.47760905e-06  3.16099894e-05 -1.63858758e-05
  2.92909857e-05]
[ 40.0572716   -4.12278708  -4.18763383 -23.55065489  -1.79225316]
16.377715672754437
next
[ 40.0572716   -4.12278708  -4.18763383 -23.55065489  -1.79225316]
[-2.27182463e-05 -1.46954511e-06  3.15744906e-05 -1.63756947e-05
  2.92603712e-05]
[ 40.05728523  -4.1227862   -4.18765278 -23.55064507  -1.79227071]
16.377715666422837
next
[ 40.05728523  -4.1227862   -4.18765278 -23.55064507  -1.79227071]
[-2.26921439e-05 -1.46149962e-06  3.15390337e-05 -1.63655142e-05
  2.92297897e-05]
[ 40.05729884  -4.12278533  -4.1876717  -23.55063525  -1.79228825]
16.37771566010459
next
[ 40.05729884  -4.12278533  -4.187671

16.37771445511756
next
[ 40.060196    -4.12269142  -4.19171033 -23.54841993  -1.79606437]
[-1.71590471e-05  3.15108209e-08  2.39955395e-05 -1.39189047e-05
  2.26457074e-05]
[ 40.06020629  -4.12269144  -4.19172473 -23.54841158  -1.79607796]
16.377714451335237
next
[ 40.06020629  -4.12269144  -4.19172473 -23.54841158  -1.79607796]
[-1.71396311e-05  3.59393428e-08  2.39689642e-05 -1.39092184e-05
  2.26222162e-05]
[ 40.06021658  -4.12269146  -4.19173911 -23.54840323  -1.79609153]
16.37771444756078
next
[ 40.06021658  -4.12269146  -4.19173911 -23.54840323  -1.79609153]
[-1.71202383e-05  4.03564062e-08  2.39424198e-05 -1.38995353e-05
  2.25987500e-05]
[ 40.06022685  -4.12269149  -4.19175347 -23.54839489  -1.79610509]
16.37771444379415
next
[ 40.06022685  -4.12269149  -4.19175347 -23.54839489  -1.79610509]
[-1.71008685e-05  4.47620337e-08  2.39159062e-05 -1.38898554e-05
  2.25753088e-05]
[ 40.06023711  -4.12269152  -4.19176782 -23.54838656  -1.79611864]
16.377714440035334
next
[ 40.06023711  

[ 40.06268488  -4.12277979  -4.19520164 -23.54628721  -1.79938912]
16.377713646094957
next
[ 40.06268488  -4.12277979  -4.19520164 -23.54628721  -1.79938912]
[-1.25018998e-05  9.00435277e-07  1.75961881e-05 -1.13329837e-05
  1.69186934e-05]
[ 40.06269238  -4.12278033  -4.1952122  -23.54628041  -1.79939927]
16.377713643980645
next
[ 40.06269238  -4.12278033  -4.1952122  -23.54628041  -1.79939927]
[-1.24879834e-05  9.02394798e-07  1.75769834e-05 -1.13243914e-05
  1.69012758e-05]
[ 40.06269987  -4.12278087  -4.19522275 -23.54627362  -1.79940941]
16.377713641870667
next
[ 40.06269987  -4.12278087  -4.19522275 -23.54627362  -1.79940941]
[-1.24740833e-05  9.04347858e-07  1.75578007e-05 -1.13158034e-05
  1.68838764e-05]
[ 40.06270736  -4.12278141  -4.19523328 -23.54626683  -1.79941954]
16.377713639765
next
[ 40.06270736  -4.12278141  -4.19523328 -23.54626683  -1.79941954]
[-1.24601994e-05  9.06294476e-07  1.75386399e-05 -1.13072198e-05
  1.68664955e-05]
[ 40.06271483  -4.12278195  -4.19524381

  1.30878585e-05]
[ 40.06432928  -4.12294339  -4.19752194 -23.54473521  -1.80163605]
16.377713230413022
next
[ 40.06432928  -4.12294339  -4.19752194 -23.54473521  -1.80163605]
[-9.47087948e-06  1.22129261e-06  1.33996933e-05 -9.31766679e-06
  1.30744640e-05]
[ 40.06433496  -4.12294412  -4.19752998 -23.54472962  -1.80164389]
16.37771322914526
next
[ 40.06433496  -4.12294412  -4.19752998 -23.54472962  -1.80164389]
[-9.46047831e-06  1.22199852e-06  1.33852417e-05 -9.31021439e-06
  1.30610834e-05]
[ 40.06434064  -4.12294486  -4.19753801 -23.54472404  -1.80165173]
16.37771322788008
next
[ 40.06434064  -4.12294486  -4.19753801 -23.54472404  -1.80165173]
[-9.45008911e-06  1.22270069e-06  1.33708063e-05 -9.30276660e-06
  1.30477169e-05]
[ 40.06434631  -4.12294559  -4.19754603 -23.54471845  -1.80165956]
16.37771322661745
next
[ 40.06434631  -4.12294559  -4.19754603 -23.54471845  -1.80165956]
[-9.43971185e-06  1.22339915e-06  1.33563872e-05 -9.29532341e-06
  1.30343643e-05]
[ 40.06435197  -4.122

[ 40.06553806  -4.1231285   -4.19923593 -23.54350628  -1.80331873]
16.377712987581386
next
[ 40.06553806  -4.1231285   -4.19923593 -23.54350628  -1.80331873]
[-7.27111820e-06  1.30109196e-06  1.03343273e-05 -7.64715689e-06
  1.02113810e-05]
[ 40.06554242  -4.12312928  -4.19924213 -23.54350169  -1.80332486]
16.377712986803914
next
[ 40.06554242  -4.12312928  -4.19924213 -23.54350169  -1.80332486]
[-7.26322809e-06  1.30110907e-06  1.03232977e-05 -7.64079959e-06
  1.02009831e-05]
[ 40.06554678  -4.12313006  -4.19924833 -23.5434971   -1.80333098]
16.377712986027998
next
[ 40.06554678  -4.12313006  -4.19924833 -23.5434971   -1.80333098]
[-7.25534692e-06  1.30112410e-06  1.03122803e-05 -7.63444669e-06
  1.01905960e-05]
[ 40.06555113  -4.12313085  -4.19925452 -23.54349252  -1.80333709]
16.37771298525365
next
[ 40.06555113  -4.12313085  -4.19925452 -23.54349252  -1.80333709]
[-7.24747468e-06  1.30113706e-06  1.03012751e-05 -7.62809818e-06
  1.01802197e-05]
[ 40.06555548  -4.12313163  -4.199260

  8.13172963e-06]
[ 40.06640978  -4.12330238  -4.2004772  -23.54256518  -1.80455149]
16.377712846716218
next
[ 40.06640978  -4.12330238  -4.2004772  -23.54256518  -1.80455149]
[-5.70238651e-06  1.26146339e-06  8.13583715e-06 -6.32473563e-06
  8.12348353e-06]
[ 40.0664132   -4.12330313  -4.20048208 -23.54256139  -1.80455637]
16.37771284622135
next
[ 40.0664132   -4.12330313  -4.20048208 -23.54256139  -1.80455637]
[-5.69626184e-06  1.26112869e-06  8.12723054e-06 -6.31932816e-06
  8.11524593e-06]
[ 40.06641662  -4.12330389  -4.20048696 -23.5425576   -1.80456124]
16.37771284572749
next
[ 40.06641662  -4.12330389  -4.20048696 -23.5425576   -1.80456124]
[-5.69014402e-06  1.26079289e-06  8.11863335e-06 -6.31392472e-06
  8.10701683e-06]
[ 40.06642003  -4.12330465  -4.20049183 -23.54255381  -1.8045661 ]
16.377712845234615
next
[ 40.06642003  -4.12330465  -4.20049183 -23.54255381  -1.8045661 ]
[-5.68403304e-06  1.26045597e-06  8.11004558e-06 -6.30852530e-06
  8.09879622e-06]
[ 40.06642344  -4.12

16.37771275016595
next
[ 40.06715273  -4.12348184  -4.20153915 -23.54172062  -1.80561711]
[-4.37903676e-06  1.15240719e-06  6.27147254e-06 -5.10645073e-06
  6.32604095e-06]
[ 40.06715536  -4.12348254  -4.20154292 -23.54171755  -1.8056209 ]
16.377712749863868
next
[ 40.06715536  -4.12348254  -4.20154292 -23.54171755  -1.8056209 ]
[-4.37438157e-06  1.15188492e-06  6.26489630e-06 -5.10197683e-06
  6.31965178e-06]
[ 40.06715798  -4.12348323  -4.20154667 -23.54171449  -1.8056247 ]
16.377712749562384
next
[ 40.06715798  -4.12348323  -4.20154667 -23.54171449  -1.8056247 ]
[-4.36973151e-06  1.15136220e-06  6.25832717e-06 -5.09750645e-06
  6.31326916e-06]
[ 40.0671606   -4.12348392  -4.20155043 -23.54171143  -1.80562848]
16.37771274926151
next
[ 40.0671606   -4.12348392  -4.20155043 -23.54171143  -1.80562848]
[-4.36508658e-06  1.15083901e-06  6.25176516e-06 -5.09303960e-06
  6.30689308e-06]
[ 40.06716322  -4.12348461  -4.20155418 -23.54170838  -1.80563227]
16.377712748961223
next
[ 40.06716322 

[ 40.06770772  -4.12363771  -4.20233525 -23.54106011  -1.80642354]
16.377712692665206
next
[ 40.06770772  -4.12363771  -4.20233525 -23.54106011  -1.80642354]
[-3.40000836e-06  1.01847085e-06  4.88532012e-06 -4.13281774e-06
  4.97082744e-06]
[ 40.06770976  -4.12363832  -4.20233818 -23.54105763  -1.80642653]
16.37771269247749
next
[ 40.06770976  -4.12363832  -4.20233818 -23.54105763  -1.80642653]
[-3.39642634e-06  1.01788671e-06  4.88023639e-06 -4.12912765e-06
  4.96582410e-06]
[ 40.0677118   -4.12363893  -4.20234111 -23.54105515  -1.80642951]
16.37771269229015
next
[ 40.0677118   -4.12363893  -4.20234111 -23.54105515  -1.80642951]
[-3.39284823e-06  1.01730248e-06  4.87515811e-06 -4.12544061e-06
  4.96082586e-06]
[ 40.06771383  -4.12363954  -4.20234404 -23.54105267  -1.80643248]
16.377712692103184
next
[ 40.06771383  -4.12363954  -4.20234404 -23.54105267  -1.80643248]
[-3.38927401e-06  1.01671817e-06  4.87008527e-06 -4.12175659e-06
  4.95583272e-06]
[ 40.06771586  -4.12364015  -4.2023469

16.377712655524622
next
[ 40.06815802  -4.12378005  -4.20298323 -23.54050263  -1.80708545]
[-2.61258784e-06  8.71588857e-07  3.76539934e-06 -3.29655055e-06
  3.86213539e-06]
[ 40.06815959  -4.12378058  -4.20298549 -23.54050065  -1.80708776]
16.377712655410566
next
[ 40.06815959  -4.12378058  -4.20298549 -23.54050065  -1.80708776]
[-2.60985872e-06  8.71011500e-07  3.76150898e-06 -3.29355940e-06
  3.85826014e-06]
[ 40.06816115  -4.1237811   -4.20298775 -23.54049867  -1.80709008]
16.377712655296737
next
[ 40.06816115  -4.1237811   -4.20298775 -23.54049867  -1.80709008]
[-2.60713252e-06  8.70434268e-07  3.75762274e-06 -3.29057078e-06
  3.85438882e-06]
[ 40.06816272  -4.12378162  -4.20299    -23.5404967   -1.80709239]
16.37771265518314
next
[ 40.06816272  -4.12378162  -4.20299    -23.5404967   -1.80709239]
[-2.60440926e-06  8.69857161e-07  3.75374063e-06 -3.28758470e-06
  3.85052144e-06]
[ 40.06816428  -4.12378214  -4.20299225 -23.54049473  -1.8070947 ]
16.37771265506975
next
[ 40.06816428 

  3.02103079e-06]
[ 40.06849833  -4.12389849  -4.20347434 -23.54006656  -1.80759087]
16.377712633294838
next
[ 40.06849833  -4.12389849  -4.20347434 -23.54006656  -1.80759087]
[-2.02223452e-06  7.34453426e-07  2.92227291e-06 -2.63288508e-06
  3.01800756e-06]
[ 40.06849955  -4.12389893  -4.2034761  -23.54006498  -1.80759268]
16.377712633224775
next
[ 40.06849955  -4.12389893  -4.2034761  -23.54006498  -1.80759268]
[-2.02013775e-06  7.33920167e-07  2.91927240e-06 -2.63046518e-06
  3.01498738e-06]
[ 40.06850076  -4.12389937  -4.20347785 -23.54006341  -1.80759449]
16.37771263315484
next
[ 40.06850076  -4.12389937  -4.20347785 -23.54006341  -1.80759449]
[-2.01804322e-06  7.33387127e-07  2.91627503e-06 -2.62804740e-06
  3.01197025e-06]
[ 40.06850197  -4.12389981  -4.2034796  -23.54006183  -1.8075963 ]
16.377712633085054
next
[ 40.06850197  -4.12389981  -4.2034796  -23.54006183  -1.8075963 ]
[-2.01595091e-06  7.32854314e-07  2.91328082e-06 -2.62563171e-06
  3.00895617e-06]
[ 40.06850318  -4.1

  2.28788183e-06]
[ 40.06879161  -4.12400918  -4.20389869 -23.53967905  -1.80803056]
16.377712618296336
next
[ 40.06879161  -4.12400918  -4.20389869 -23.53967905  -1.80803056]
[-1.51724545e-06  5.95504845e-07  2.19826727e-06 -2.03578905e-06
  2.28559823e-06]
[ 40.06879252  -4.12400954  -4.20390001 -23.53967783  -1.80803193]
16.377712618255895
next
[ 40.06879252  -4.12400954  -4.20390001 -23.53967783  -1.80803193]
[-1.51568393e-06  5.95040552e-07  2.19602403e-06 -2.03389567e-06
  2.28331693e-06]
[ 40.06879343  -4.12400989  -4.20390133 -23.53967661  -1.8080333 ]
16.37771261821553
next
[ 40.06879343  -4.12400989  -4.20390133 -23.53967661  -1.8080333 ]
[-1.51412405e-06  5.94576525e-07  2.19378314e-06 -2.03200398e-06
  2.28103793e-06]
[ 40.06879434  -4.12401025  -4.20390264 -23.53967539  -1.80803467]
16.377712618175252
next
[ 40.06879434  -4.12401025  -4.20390264 -23.53967539  -1.80803467]
[-1.51256582e-06  5.94112760e-07  2.19154457e-06 -2.03011398e-06
  2.27876122e-06]
[ 40.06879525  -4.1

[ 40.06895849  -4.12407622  -4.20414067 -23.53945305  -1.80828268]
16.377712611526974
next
[ 40.06895849  -4.12407622  -4.20414067 -23.53945305  -1.80828268]
[-1.23167398e-06  5.06685185e-07  1.78751934e-06 -1.68421718e-06
  1.86652574e-06]
[ 40.06895923  -4.12407652  -4.20414174 -23.53945204  -1.8082838 ]
16.3777126114999
next
[ 40.06895923  -4.12407652  -4.20414174 -23.53945204  -1.8082838 ]
[-1.23041246e-06  5.06274686e-07  1.78570251e-06 -1.68263947e-06
  1.86466581e-06]
[ 40.06895997  -4.12407683  -4.20414281 -23.53945103  -1.80828492]
16.377712611472873
next
[ 40.06895997  -4.12407683  -4.20414281 -23.53945103  -1.80828492]
[-1.22915226e-06  5.05864452e-07  1.78388755e-06 -1.68106319e-06
  1.86280775e-06]
[ 40.0689607   -4.12407713  -4.20414388 -23.53945002  -1.80828604]
16.377712611445897
next
[ 40.0689607   -4.12407713  -4.20414388 -23.53945002  -1.80828604]
[-1.22789338e-06  5.05454480e-07  1.78207448e-06 -1.67948833e-06
  1.86095155e-06]
[ 40.06896144  -4.12407743  -4.2041449

16.377712606227526
next
[ 40.06911987  -4.12414421  -4.20437509 -23.53923019  -1.80852801]
[-9.56888714e-07  4.13174127e-07  1.39124683e-06 -1.33499591e-06
  1.45943730e-06]
[ 40.06912044  -4.12414446  -4.20437592 -23.53922939  -1.80852889]
16.377712606210892
next
[ 40.06912044  -4.12414446  -4.20437592 -23.53922939  -1.80852889]
[-9.55913755e-07  4.12827009e-07  1.38983885e-06 -1.33373602e-06
  1.45798559e-06]
[ 40.06912102  -4.12414471  -4.20437676 -23.53922859  -1.80852976]
16.37771260619429
next
[ 40.06912102  -4.12414471  -4.20437676 -23.53922859  -1.80852976]
[-9.54939809e-07  4.12480137e-07  1.38843231e-06 -1.33247729e-06
  1.45653534e-06]
[ 40.06912159  -4.12414496  -4.20437759 -23.53922779  -1.80853064]
16.377712606177717
next
[ 40.06912159  -4.12414496  -4.20437759 -23.53922779  -1.80853064]
[-9.53966873e-07  4.12133514e-07  1.38702721e-06 -1.33121970e-06
  1.45508653e-06]
[ 40.06912216  -4.12414521  -4.20437842 -23.53922699  -1.80853151]
16.377712606161186
next
[ 40.06912216

16.377712603299056
next
[ 40.06923125  -4.12419317  -4.20453714 -23.53907363  -1.8086983 ]
[-7.68121840e-07  3.43767905e-07  1.11835575e-06 -1.08807545e-06
  1.17731404e-06]
[ 40.06923171  -4.12419337  -4.20453781 -23.53907298  -1.80869901]
16.377712603288195
next
[ 40.06923171  -4.12419337  -4.20453781 -23.53907298  -1.80869901]
[-7.67342382e-07  3.43471790e-07  1.11722770e-06 -1.08704293e-06
  1.17614454e-06]
[ 40.06923217  -4.12419358  -4.20453848 -23.53907232  -1.80869971]
16.377712603277352
next
[ 40.06923217  -4.12419358  -4.20453848 -23.53907232  -1.80869971]
[-7.66563726e-07  3.43175900e-07  1.11610080e-06 -1.08601136e-06
  1.17497622e-06]
[ 40.06923263  -4.12419378  -4.20453915 -23.53907167  -1.80870042]
16.37771260326653
next
[ 40.06923263  -4.12419378  -4.20453915 -23.53907167  -1.80870042]
[-7.65785878e-07  3.42880233e-07  1.11497505e-06 -1.08498076e-06
  1.17380905e-06]
[ 40.06923309  -4.12419399  -4.20453982 -23.53907102  -1.80870112]
16.377712603255734
next
[ 40.06923309

16.37771260108029
next
[ 40.06933699  -4.12424135  -4.20469121 -23.53892267  -1.80886078]
[-5.89659522e-07  2.73751800e-07  8.59793598e-07 -8.48659691e-07
  9.08489804e-07]
[ 40.06933735  -4.12424152  -4.20469172 -23.53892216  -1.80886133]
16.377712601073785
next
[ 40.06933735  -4.12424152  -4.20469172 -23.53892216  -1.80886133]
[-5.89063742e-07  2.73510255e-07  8.58929404e-07 -8.47849825e-07
  9.07588630e-07]
[ 40.0693377   -4.12424168  -4.20469224 -23.53892165  -1.80886187]
16.377712601067312
next
[ 40.0693377   -4.12424168  -4.20469224 -23.53892165  -1.80886187]
[-5.88468568e-07  2.73268905e-07  8.58066091e-07 -8.47040714e-07
  9.06688357e-07]
[ 40.06933805  -4.12424185  -4.20469275 -23.53892114  -1.80886242]
16.377712601060846
next
[ 40.06933805  -4.12424185  -4.20469275 -23.53892114  -1.80886242]
[-5.87874013e-07  2.73027745e-07  8.57203653e-07 -8.46232363e-07
  9.05788977e-07]
[ 40.06933841  -4.12424201  -4.20469327 -23.53892064  -1.80886296]
16.377712601054387
next
[ 40.06933841

  7.23890413e-07]
[ 40.06940964  -4.12427554  -4.2047972  -23.53881749  -1.80897294]
16.37771259987799
next
[ 40.06940964  -4.12427554  -4.2047972  -23.53881749  -1.80897294]
[-4.67516322e-07  2.23052102e-07  6.82469662e-07 -6.81023870e-07
  7.23173130e-07]
[ 40.06940993  -4.12427567  -4.20479761 -23.53881708  -1.80897337]
16.377712599873863
next
[ 40.06940993  -4.12427567  -4.20479761 -23.53881708  -1.80897337]
[-4.67045527e-07  2.22851918e-07  6.81785558e-07 -6.80371255e-07
  7.22456557e-07]
[ 40.06941021  -4.12427581  -4.20479802 -23.53881667  -1.8089738 ]
16.377712599869742
next
[ 40.06941021  -4.12427581  -4.20479802 -23.53881667  -1.8089738 ]
[-4.66575210e-07  2.22651902e-07  6.81102150e-07 -6.79719253e-07
  7.21740700e-07]
[ 40.06941049  -4.12427594  -4.20479843 -23.53881626  -1.80897424]
16.37771259986563
next
[ 40.06941049  -4.12427594  -4.20479843 -23.53881626  -1.80897424]
[-4.66105377e-07  2.22452050e-07  6.80419431e-07 -6.79067868e-07
  7.21025552e-07]
[ 40.06941077  -4.12

[ 40.06946904  -4.12430422  -4.20488395 -23.5387305   -1.80906498]
[-3.67974699e-07  1.79849074e-07  5.37714693e-07 -5.41847563e-07
  5.71247128e-07]
[ 40.06946926  -4.12430432  -4.20488427 -23.53873018  -1.80906532]
16.377712599090337
next
[ 40.06946926  -4.12430432  -4.20488427 -23.53873018  -1.80906532]
[-3.67605268e-07  1.79685320e-07  5.37177017e-07 -5.41326399e-07
  5.70681648e-07]
[ 40.06946948  -4.12430443  -4.2048846  -23.53872985  -1.80906566]
16.37771259908775
next
[ 40.06946948  -4.12430443  -4.2048846  -23.53872985  -1.80906566]
[-3.67236215e-07  1.79521705e-07  5.36639882e-07 -5.40805730e-07
  5.70116728e-07]
[ 40.0694697   -4.12430454  -4.20488492 -23.53872953  -1.809066  ]
16.377712599085186
next
[ 40.0694697   -4.12430454  -4.20488492 -23.53872953  -1.809066  ]
[-3.66867525e-07  1.79358235e-07  5.36103296e-07 -5.40285548e-07
  5.69552376e-07]
[ 40.06946992  -4.12430465  -4.20488524 -23.53872921  -1.80906635]
16.377712599082617
next
[ 40.06946992  -4.12430465  -4.204885

[-2.90987989e-07  1.45136841e-07  4.25591781e-07 -4.32443280e-07
  4.53125256e-07]
[ 40.06951529  -4.12432704  -4.20495156 -23.5386621   -1.80913687]
16.377712598606514
next
[ 40.06951529  -4.12432704  -4.20495156 -23.5386621   -1.80913687]
[-2.90696608e-07  1.45003140e-07  4.25167123e-07 -4.32026049e-07
  4.52677083e-07]
[ 40.06951546  -4.12432713  -4.20495181 -23.53866184  -1.80913715]
16.377712598604887
next
[ 40.06951546  -4.12432713  -4.20495181 -23.53866184  -1.80913715]
[-2.90405528e-07  1.44869553e-07  4.24742889e-07 -4.31609220e-07
  4.52229351e-07]
[ 40.06951563  -4.12432722  -4.20495207 -23.53866158  -1.80913742]
16.377712598603264
next
[ 40.06951563  -4.12432722  -4.20495207 -23.53866158  -1.80913742]
[-2.90114737e-07  1.44736086e-07  4.24319085e-07 -4.31192784e-07
  4.51782067e-07]
[ 40.06951581  -4.12432731  -4.20495232 -23.53866132  -1.80913769]
16.377712598601647
next
[ 40.06951581  -4.12432731  -4.20495232 -23.53866132  -1.80913769]
[-2.89824241e-07  1.44602735e-07  4.

In [54]:
print(m)   #show the coefficients


[ 40.06952363  -4.12433121  -4.20496376 -23.53864969  -1.80914987]


In [55]:
#Xt=x.transpose
#print(x.shape)
#print(x.transpose)
#xtx=x.T.dot(x)
#print(xtx.shape)
#BB=np.linalg.inv(xtx)
#xy=y.dot(x)
#print(xy.shape)
#BBB=BB.dot(xy)
#print(BBB)

BBB= np.linalg.pinv((x.T).dot(x)).dot(x.T.dot(y))   #closed form solution
print(BBB)

[ 45.2511397   -2.7303963  -10.0297781  -27.14181008  -0.57407038]


In [56]:
# Hardcoded as shown in the lecture notes
#def ML_Regression(x,y):
#    beta = np.linalg.pinv((x.T).dot(x)).dot(x.T.dot(y))
#    return beta

In [57]:
#beta=ML_Regression(x,y)
#beta

In [58]:
def Prediction_ML(m, x_test):    #use the coefficients from grad descent to predict y using test data
    y_pred = x_test.dot(m)
    return y_pred

In [59]:
y_pred=Prediction_ML(m,x_test)
print(stats.pearsonr(y_pred,y_test))  #print the pearson correlation and p-value

(0.8124897471091576, 5.922645897254911e-29)


In [60]:
# PART 2

In [61]:
#1.
CarData=pd.read_csv('AutoData.csv',usecols=[0,1,2,3,4,5,6,7])
CarData.head(5)


mpg  cylinder  displacement  horsepower  weight  accelaration  model_year  \
0  18.0         8         307.0         130    3504          12.0          70   
1  15.0         8         350.0         165    3693          11.5          70   
2  18.0         8         318.0         150    3436          11.0          70   
3  16.0         8         304.0         150    3433          12.0          70   
4  17.0         8         302.0         140    3449          10.5          70   

   origin  
0       1  
1       1  
2       1  
3       1  
4       1

In [62]:
CarData.corr()
#The variables that affect MPG the most are weight (-.832244), displacement (-.805127), 
# and horsepower (-.778427) because of their higher absolute correlation coefficients

mpg  cylinder  displacement  horsepower    weight  \
mpg           1.000000 -0.777618     -0.805127   -0.778427 -0.832244   
cylinder     -0.777618  1.000000      0.950823    0.842983  0.897527   
displacement -0.805127  0.950823      1.000000    0.897257  0.932994   
horsepower   -0.778427  0.842983      0.897257    1.000000  0.864538   
weight       -0.832244  0.897527      0.932994    0.864538  1.000000   
accelaration  0.423329 -0.504683     -0.543800   -0.689196 -0.416839   
model_year    0.580541 -0.345647     -0.369855   -0.416361 -0.309120   
origin        0.565209 -0.568932     -0.614535   -0.455171 -0.585005   

              accelaration  model_year    origin  
mpg               0.423329    0.580541  0.565209  
cylinder         -0.504683   -0.345647 -0.568932  
displacement     -0.543800   -0.369855 -0.614535  
horsepower       -0.689196   -0.416361 -0.455171  
weight           -0.416839   -0.309120 -0.585005  
accelaration      1.000000    0.290316  0.212746  
model_year        0.290316    1.000000  0.181528  
origin            0.212746    0.181528  1.000000

In [63]:
#2.
#Fit a regression model to predict mpg using all variables except car name
Y_pred_Car = smf.ols("mpg ~ cylinder + displacement + horsepower  + weight + accelaration + model_year + origin", CarData).fit()

In [64]:
Y_pred_Car.summary().tables[1]
#We can remove cylinder, horsepower, and acceleration because of their high p-value
#the variables best suited to build the model to predict mpg are displacement, weight, model year and origing
#because of their low p-value indicating high significance

<class 'statsmodels.iolib.table.SimpleTable'>

In [65]:
Y_pred_Car = smf.ols("mpg ~ displacement + weight + model_year + origin", CarData).fit()

In [66]:
Y_pred_Car.summary().tables[1]
#remove displacemnet beause of high p-value

<class 'statsmodels.iolib.table.SimpleTable'>

In [67]:
#  Updated model for reduced number of variables
Y_pred_Car = smf.ols("mpg ~ weight + model_year + origin", CarData).fit()
Y_pred_Car.summary().tables[1]

<class 'statsmodels.iolib.table.SimpleTable'>

In [68]:
#3.
# Interaction between horsepower and weight
Y_pred_hp_wt = smf.ols("mpg ~ cylinder + displacement + horsepower  + weight + accelaration + model_year + origin + displacement*weight", CarData).fit()
Y_pred_hp_wt.summary().tables[1]


<class 'statsmodels.iolib.table.SimpleTable'>

In [69]:
#remove cylinder and acceleration because of high p-values
Y_pred_hp_wt = smf.ols("mpg ~ displacement + horsepower  + weight + model_year + origin + displacement*weight", CarData).fit()
Y_pred_hp_wt.summary().tables[1]


<class 'statsmodels.iolib.table.SimpleTable'>

In [70]:
print(Y_pred_hp_wt.params[2])
BE=Y_pred_hp_wt.params[0:7]
x_test=Data[:,[2,3,4,6, 7]]
x_test=np.insert(x_test,5,np.multiply(x_test[:,0],x_test[:,2]), axis=1)
x_test=np.insert(x_test,0,1, axis=1)
y_test=Data[:,0]

y_pred=Prediction_ML(BE,x_test)
print(stats.pearsonr(y_pred,y_test))

#The interaction term did improve the model as the higher pierson correlation and lower p-value indicates. 
# I believe the model was improved because 
#a high motor displacement and low weight could increase mpg and a low motor displacement 
#and high weight could reduce mpg.
# This means that a direct correlation of weight and mpg cannot be precisely formulated 
# because it also depends on the interaction with motor displacement. 



-0.03889708276094417
(0.9265482404531229, 1.1004918671636827e-167)
