In [2]:
#Import libraries 
import numpy as np 
import matplotlib
import matplotlib.pyplot as plt 
from scipy.spatial import distance
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import classification_report

from sklearn.model_selection import train_test_split

import matplotlib.pyplot as plt
import pandas as pd
%matplotlib inline
import numpy as np



In [3]:
#Import EMG Dataset
X = np.genfromtxt('traing_matrix05.csv', delimiter=',', skip_header=2)
X1 = np.genfromtxt('test_matrix05.csv', delimiter=',', skip_header=2)

m,n = np.shape(X)

x_train = []
y_train = [] 
x_test = []
y_test = []


#Split data x_train, y_train
x_train = X[:,0:n-7]
y_train = X[:,65:71]


#Test data 
x_test = X1[:,0:n-7]
y_test = X1[:,65:71]

y_class_test=X1[:,64]

In [10]:
from sklearn.cluster import KMeans
clus=6



xx1_train=((x_train))
kmeans = KMeans(n_clusters=clus, random_state=0).fit(xx1_train)
clusters=kmeans.labels_

cy=kmeans.predict(x_test)
cx1=[]
cy1=[]

for i in range (0,clus):
        cx1.append([])
        cy1.append([])
        h=0
        for j in range (len(clusters)-1):
            
            if clusters[j]==i:
                cx1[i].append([])
                cy1[i].append([])
                cx1[i][h]=x_train[j,:]
                cy1[i][h]=y_train[j,:]
                h=h+1
    



In [29]:
print(np.shape(cy1))
print(np.shape(cx1))
print(cy1[0][4])
print(cy)


(6,)
(6,)
[0. 0. 0. 0. 1. 0.]
[5 4 0 2 2 3 5 0 2 2 3 3 2 4 0 2 2 3 3 0 2 2 3 3 2 4 0 2 5 2 3 4 0 2 5 3 5
 0 0 2 2 0 5 0 2 5 3 3 1 4 0 2 2 3 1 0 2 2 3 3 5 4 0 2 2 3 2 0 2 0 3 3 1 4
 0 3 2 3 1 0 2 1 3 3 1 4 0 2 2 0 1 0 2 2 3 3 5 5 2 5 0 0 5 4 5 2 5 0 4 0 3
 5 3 3 2 0 2 2 3 3 4 5 2 2 3 3 5 5 2 5 3 3 1 0 2 5 0 0 1 0 2 2 3 3 1 5 2 2
 3 3 2 0 2 2 3 3 5 0 2 0 2 2 5 0 5 5 2 2 5 0 2 2 3 3 1 0 2 2 0 0 1 0 2 5 3
 3 5 0 2 2 3 3 5 0 2 2 0 0 5 0 4 2 0 0 1 3 2 5 3 3 1 1 2 2 0 0 5 0 2 5 3 3
 5 0 2 2 3 3 1 0 2 2 3 3 5 0 2 2 3 3]


In [61]:
prob1=[]

for i in range (0, clus):
    prob1.append([])
    prob1[i]= np.sum(cy1[i],axis=0)/np.sum(np.sum(cy1[i],axis=0),axis=0)
    

In [62]:
print(prob1[0])
print(prob1[1])
print(prob1[2])
print(prob1[3])
print(prob1[4])
print(prob1[5])

[0.02608696 0.35652174 0.4173913  0.         0.05217391 0.14782609]
[0.8   0.    0.    0.075 0.1   0.025]
[0.02564103 0.00641026 0.23076923 0.48717949 0.23076923 0.01923077]
[0.03225806 0.0483871  0.0483871  0.         0.24193548 0.62903226]
[0.14942529 0.59770115 0.04597701 0.08045977 0.08045977 0.04597701]
[0.47524752 0.03960396 0.0990099  0.17821782 0.20792079 0.        ]


In [79]:
cy_prob1=[]
cy_pred=[]
cy1_binary=[]

for f in range(len(x_test)):
    cy_prob1.append([])
    cy1_binary.append([])
    cy_prob1[f]=prob1[cy[f]]
    cy1_binary[f]=[1 if x == max(cy_prob1[f]) else 0 for x in cy_prob1[f]]
    
    
   
        
       # for j in range (len(clusters[f])-1):
#check for any of equal probability
db=[]
for f in range (len(x_test)):
    cy_pred.append([])
    cy_pred[f]=cy1_binary[f]
    if np.sum(cy1_binary[f]) != 6:
        db.append([f])
        
#db = 117 and 170 have double probability


In [85]:
for i in range (len(y_test)):
    
    print(cy1_binary[i])
    print(y_test[i])
    print('-----')
#print(cy1_binary)
#print(cy_prob1)
#print(db)



[1, 0, 0, 0, 0, 0]
[1. 0. 0. 0. 0. 0.]
-----
[0, 1, 0, 0, 0, 0]
[0. 1. 0. 0. 0. 0.]
-----
[0, 0, 1, 0, 0, 0]
[0. 0. 1. 0. 0. 0.]
-----
[0, 0, 0, 1, 0, 0]
[0. 0. 0. 1. 0. 0.]
-----
[0, 0, 0, 1, 0, 0]
[0. 0. 0. 0. 1. 0.]
-----
[0, 0, 0, 0, 0, 1]
[0. 0. 0. 0. 0. 1.]
-----
[1, 0, 0, 0, 0, 0]
[1. 0. 0. 0. 0. 0.]
-----
[0, 0, 1, 0, 0, 0]
[0. 1. 0. 0. 0. 0.]
-----
[0, 0, 0, 1, 0, 0]
[0. 0. 1. 0. 0. 0.]
-----
[0, 0, 0, 1, 0, 0]
[0. 0. 0. 1. 0. 0.]
-----
[0, 0, 0, 0, 0, 1]
[0. 0. 0. 0. 1. 0.]
-----
[0, 0, 0, 0, 0, 1]
[0. 0. 0. 0. 0. 1.]
-----
[0, 0, 0, 1, 0, 0]
[1. 0. 0. 0. 0. 0.]
-----
[0, 1, 0, 0, 0, 0]
[0. 1. 0. 0. 0. 0.]
-----
[0, 0, 1, 0, 0, 0]
[0. 0. 1. 0. 0. 0.]
-----
[0, 0, 0, 1, 0, 0]
[0. 0. 0. 1. 0. 0.]
-----
[0, 0, 0, 1, 0, 0]
[0. 0. 0. 0. 1. 0.]
-----
[0, 0, 0, 0, 0, 1]
[0. 0. 0. 0. 0. 1.]
-----
[0, 0, 0, 0, 0, 1]
[1. 0. 0. 0. 0. 0.]
-----
[0, 0, 1, 0, 0, 0]
[0. 1. 0. 0. 0. 0.]
-----
[0, 0, 0, 1, 0, 0]
[0. 0. 1. 0. 0. 0.]
-----
[0, 0, 0, 1, 0, 0]
[0. 0. 0. 1. 0. 0.]
-----
[0, 0, 0, 

In [77]:
mat=[]
error=0
for f in range(len(x_test)):
    mat.append([])
    
    for i in range (0,6):
        mat[f].append([])
        mat[f][i]=y_test[f][i]-cy1_binary[f][i]
        if mat[f][i] != 0:
            error=error+1
error=error/2/len(y_test)  #divide by two because every miss increases error by 2

    
    

In [78]:
print(error)

0.5666666666666667
